---
- name: Converge the fleet
  hosts: all
  become: true
  roles:
    - place_base
    - place_net
    - place_shell

- name: Converge storage
  hosts: storage
  become: true
  roles:
    - place_storage
